# Generated by Django 2.2.13 on 2020-08-01 10:58

from django.db import migrations, models
import django.db.models.deletion
import inloop.medics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0007_merge_20190802_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('profession', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medics.Medic')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('priority', models.TextField(validators=[inloop.medics.models.validate_priority])),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('end_line', models.IntegerField(blank=True, null=True)),
                ('start_column', models.IntegerField(blank=True, null=True)),
                ('end_column', models.IntegerField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medics.Rule')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution')),
                ('solution_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.SolutionFile')),
            ],
        ),
    ]
