# Generated by Django 2.2.13 on 2020-08-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
    ]
