# Generated by Django 2.2.13 on 2020-08-03 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_merge_20190802_1345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medics', '0003_remove_notification_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='style',
            field=models.TextField(default='info'),
        ),
        migrations.CreateModel(
            name='SolutionScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medics.Score')),
                ('solution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution')),
            ],
            bases=('medics.score',),
        ),
    ]
