# Generated by Django 2.2.13 on 2020-08-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_default_ordering_by_title'),
        ('medics', '0005_auto_20200803_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medics.Score')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            bases=('medics.score',),
        ),
        migrations.RemoveField(
            model_name='solutionviolationscore',
            name='score_ptr',
        ),
        migrations.RemoveField(
            model_name='solutionviolationscore',
            name='solution',
        ),
        migrations.DeleteModel(
            name='SolutionPassedScore',
        ),
        migrations.DeleteModel(
            name='SolutionViolationScore',
        ),
    ]
