# Generated by Django 2.2.13 on 2020-08-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_merge_20190802_1345'),
        ('medics', '0006_auto_20200803_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medics.Score')),
                ('solution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution')),
            ],
            bases=('medics.score',),
        ),
        migrations.AddField(
            model_name='score',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TaskScore',
        ),
    ]
