# Generated by Django 2.2.13 on 2020-08-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0009_playerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColleagueTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_colleague', to='medics.PlayerDetails')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='medics.PlayerDetails')),
            ],
        ),
    ]
