# Generated by Django 2.2.13 on 2020-08-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0010_colleaguetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='colleaguetracker',
            name='tracked_colleague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_colleague_set', to='medics.PlayerDetails'),
        ),
        migrations.AlterField(
            model_name='colleaguetracker',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_set', to='medics.PlayerDetails'),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medics.Avatar'),
        ),
    ]
