# Generated by Django 2.2.13 on 2020-08-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0011_auto_20200810_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
                ('reward', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BadgeScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medics.Score')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medics.Badge')),
            ],
            bases=('medics.score',),
        ),
    ]
