# Generated by Django 2.2.13 on 2020-08-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_default_ordering_by_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='achievable_points',
            field=models.IntegerField(default=1000),
        ),
    ]
